version: "3.9"

services:
#  app:
#    build: .
#    container_name: worknest-api
#    restart: unless-stopped
#    env_file:
#      - .env
#    environment:
#      DB_HOST: postgres
#      DB_PORT: 5432
#      DB_NAME: worknest_db
#      DB_USERNAME: root
#      DB_PASSWORD: root
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/worknest_db
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
#    ports:
#      - "8080:8080"
#    depends_on:
#      postgres:
#        condition: service_healthy

  postgres:
    image: postgres:15-alpine
    container_name: worknest-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-worknest_db}
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-root} -d ${POSTGRES_DB:-worknest_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=worknest_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - ./src/main/resources/db/seed/seed-dev.sql:/docker-entrypoint-initdb.d/seed-dev.sql


volumes:
  postgres_data: